version: "3.8"

services:

  mock-api:
    image: clue/json-server
    volumes:
      - ./mock-api/db.json:/data/db.json
      - ./mock-api/routes.json:/data/routes.json
    command: --watch /data/db.json --routes /data/routes.json --host 0.0.0.0
    ports:
      - 8081:80
    networks:
      - banco-network
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - banco-network
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - banco-network
networks:
  banco-network:
    driver: bridge