spring:
  application:
    name: desafioconta
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


mock:
  api:
    url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
