spring:
  application:
    name: desafioconta

mock:
  api:
    url: http://mock-api:80

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true